import { ShieldWarning } from "@phosphor-icons/react";
import { formatMemoryTokens, type AgentMemoryCompactionPreview, type AgentMemoryCompactionReceipt } from "../lib/agentMemory";

export function AgentMemoryDiffPreview({ preview, receipt, canApply, applying, confirmationPhrase, onConfirmationChange, onApply, onRollback }: { preview: AgentMemoryCompactionPreview | null; receipt: AgentMemoryCompactionReceipt | null; canApply: boolean; applying: boolean; confirmationPhrase: string; onConfirmationChange: (value: string) => void; onApply: () => void; onRollback: () => void }) {
  if (!preview) return null;
  const blocked = preview.secretScan.status === "blocked";
  return <article className="repo-map-panel" aria-live="polite"><div className="repo-map-panel__header"><h2>Compaction preview</h2><span className="repo-intelligence-view__badge">Read-only</span></div>
    <p>{preview.summary ?? "This preview never writes to an agent memory file."}</p>
    <div className="repo-map-metrics"><div><dt>Before</dt><dd>{formatMemoryTokens(preview.beforeTokens)}</dd></div><div><dt>After</dt><dd>{formatMemoryTokens(preview.afterTokens)}</dd></div><div><dt>Duplicate removed</dt><dd>{formatMemoryTokens(preview.duplicateTokensRemoved)}</dd></div></div>
    {blocked ? <p className="repo-map-error"><ShieldWarning size={16} /> Preview content is blocked: {preview.secretScan.reason ?? "secret scan requires review"}. No content is rendered or copied.</p> : preview.diff ? <pre className="optimize-minimal__meta"><code>{preview.diff}</code></pre> : <p>No bounded diff was available for this source.</p>}
    {canApply ? <div className="agent-memory-confirmation"><p><strong>Apply this managed change?</strong> A timestamped backup is created first. Type <code>{preview.confirmationPhrase}</code> to confirm.</p><input aria-label="Apply memory confirmation" value={confirmationPhrase} onChange={(event) => onConfirmationChange(event.target.value)} placeholder={preview.confirmationPhrase ?? "Confirmation phrase"} /><button className="primary-button" disabled={applying || confirmationPhrase !== preview.confirmationPhrase} onClick={onApply} type="button">{applying ? "Applying…" : "Apply compaction"}</button></div> : !blocked ? <p className="optimize-minimal__meta">{preview.applyBlockedReason ?? "Apply is only available for safe, Switchboard-managed sources. User-managed and blocked sources remain read-only."}</p> : null}
    {receipt ? <div className="agent-memory-receipt" role="status"><p><strong>{receipt.summary ?? "Managed memory change recorded."}</strong></p><p>Backup: {receipt.backupPath ?? "Backup location unavailable"}</p><p>Receipt: {receipt.receiptId || "Unavailable"}</p>{receipt.rollbackAvailable && receipt.rollbackConfirmationPhrase ? <><p>To roll back, type <code>{receipt.rollbackConfirmationPhrase}</code>. The original backup is restored only after this confirmation.</p><input aria-label="Rollback memory confirmation" value={confirmationPhrase} onChange={(event) => onConfirmationChange(event.target.value)} placeholder={receipt.rollbackConfirmationPhrase} /><button className="secondary-button secondary-button--small" disabled={applying || confirmationPhrase !== receipt.rollbackConfirmationPhrase} onClick={onRollback} type="button">Rollback using backup</button></> : null}</div> : null}
  </article>;
}
