import { ArrowClockwise, Brain, Copy, ShieldWarning } from "@phosphor-icons/react";
import { useEffect, useState } from "react";
import { applyAgentMemoryCompaction, buildSafeMemorySummary, canApplyAgentMemoryCompaction, getAgentMemorySnapshot, previewAgentMemoryCompaction, rollbackAgentMemoryCompaction, type AgentMemoryCompactionPreview, type AgentMemoryCompactionReceipt, type AgentMemorySource, type AgentMemorySnapshot } from "../lib/agentMemory";
import { AgentMemoryDiffPreview } from "./AgentMemoryDiffPreview";
import { AgentMemorySourceList } from "./AgentMemorySourceList";

export function AgentMemoryInspector({ hidden }: { hidden: boolean }) {
  const [snapshot, setSnapshot] = useState<AgentMemorySnapshot | null>(null); const [repoPath, setRepoPath] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [preview, setPreview] = useState<AgentMemoryCompactionPreview | null>(null); const [selectedSource, setSelectedSource] = useState<AgentMemorySource | null>(null); const [previewError, setPreviewError] = useState<string | null>(null); const [copied, setCopied] = useState(false); const [confirmationPhrase, setConfirmationPhrase] = useState(""); const [receipt, setReceipt] = useState<AgentMemoryCompactionReceipt | null>(null); const [applying, setApplying] = useState(false);
  const refresh = async () => { setLoading(true); setError(null); setPreview(null); setSelectedSource(null); setReceipt(null); setConfirmationPhrase(""); try { setSnapshot(await getAgentMemorySnapshot(repoPath)); } catch (reason) { setSnapshot(null); setError(reason instanceof Error ? reason.message : "Agent Memory is unavailable."); } finally { setLoading(false); } };
  useEffect(() => { if (!hidden) void refresh(); }, [hidden]);
  const inspectPreview = async (source: AgentMemorySource) => { const path = repoPath.trim() || snapshot?.repoPath; if (!path) { setPreviewError("Enter a repository path to generate a bounded compaction preview."); return; } setPreviewError(null); setPreview(null); setSelectedSource(source); setReceipt(null); setConfirmationPhrase(""); try { setPreview(await previewAgentMemoryCompaction(path, source.agent)); } catch (reason) { setPreviewError(reason instanceof Error ? reason.message : "Compaction preview is unavailable."); } };
  const applyPreview = async () => { const path = repoPath.trim() || snapshot?.repoPath; if (!path || !selectedSource || confirmationPhrase !== preview?.confirmationPhrase) return; setApplying(true); setPreviewError(null); try { setReceipt(await applyAgentMemoryCompaction(path, selectedSource.agent, confirmationPhrase)); setConfirmationPhrase(""); setSnapshot(await getAgentMemorySnapshot(repoPath)); } catch (reason) { setPreviewError(reason instanceof Error ? reason.message : "Compaction could not be applied. No change was confirmed."); } finally { setApplying(false); } };
  const rollback = async () => { if (!receipt?.receiptId || confirmationPhrase !== receipt.rollbackConfirmationPhrase) return; setApplying(true); setPreviewError(null); try { setReceipt(await rollbackAgentMemoryCompaction(receipt.receiptId, confirmationPhrase)); setConfirmationPhrase(""); setSnapshot(await getAgentMemorySnapshot(repoPath)); } catch (reason) { setPreviewError(reason instanceof Error ? reason.message : "Rollback could not be completed. The backup remains unchanged."); } finally { setApplying(false); } };
  const copySummary = async () => { if (!snapshot) return; await navigator.clipboard?.writeText(buildSafeMemorySummary(snapshot)); setCopied(true); window.setTimeout(() => setCopied(false), 1400); };
  return <div className="tray-content" hidden={hidden}><section className="repo-intelligence-view" aria-labelledby="agent-memory-title"><header className="repo-intelligence-view__header"><div><h1 id="agent-memory-title">Agent Memory</h1><p className="repo-intelligence-view__subtitle">Inspect local memory before a session. Previews are read-only; no agent files are changed.</p></div><button className="secondary-button secondary-button--small" disabled={loading} onClick={() => void refresh()} type="button"><ArrowClockwise className={loading ? "is-spinning" : undefined} size={15} />Refresh</button></header>
    <article className="repo-map-panel"><label className="optimize-project-row"><span className="optimize-project-row__main"><span className="optimize-project-row__name">Repository path (optional)</span><input aria-label="Repository path" onChange={(event) => setRepoPath(event.target.value)} placeholder="Use the current workspace" value={repoPath} /></span></label><p className="optimize-minimal__meta">Sources include Codex, Claude, AGENTS.md, CLAUDE.md, session packs, and Repo Memory MCP when available. Memory contents are never included in this inventory.</p></article>
    {error ? <article className="repo-map-error" role="alert"><ShieldWarning size={16} /> {error} The native Agent Memory backend may not be available yet. Retry after it is installed.</article> : null}
    {loading ? <div className="savings-chart__skeleton" role="status"><p className="loading-copy">Reading local memory metadata…</p></div> : null}
    {!loading && !error && snapshot ? <><article className="repo-map-hero repo-map-hero--healthy"><div className="repo-map-hero__icon"><Brain size={28} weight="duotone" /></div><div className="repo-map-hero__copy"><p className="repo-map-eyebrow">Local inventory</p><h2>{snapshot.sources.length} source{snapshot.sources.length === 1 ? "" : "s"}</h2><p>{snapshot.repoPath ?? "Current workspace or global scope"}</p></div><button className="secondary-button secondary-button--small" onClick={() => void copySummary()} type="button"><Copy size={14} />{copied ? "Copied" : "Copy safe summary"}</button></article><AgentMemorySourceList onPreview={(source) => void inspectPreview(source)} sources={snapshot.sources} />{previewError ? <article className="repo-map-error" role="alert">{previewError}</article> : null}<AgentMemoryDiffPreview applying={applying} canApply={!receipt && selectedSource ? canApplyAgentMemoryCompaction(selectedSource, preview) : false} confirmationPhrase={confirmationPhrase} onApply={() => void applyPreview()} onConfirmationChange={setConfirmationPhrase} onRollback={() => void rollback()} preview={preview} receipt={receipt} /></> : null}
  </section></div>;
}
