use std::path::{Path, PathBuf};

use chrono::{DateTime, NaiveDate, Utc};

use crate::models::AppliedSection;

#[derive(Debug, Clone)]
pub(crate) struct HeadroomLearnMetadata {
    pub(crate) learned_at: Option<String>,
    pub(crate) pattern_count: Option<usize>,
}

#[derive(Debug, Clone)]
pub struct HeadroomLearnProjectSummary {
    pub last_run_at: Option<String>,
    pub has_persisted_learnings: bool,
    pub pattern_count: Option<usize>,
}

#[derive(Debug, Clone)]
pub(crate) struct HeadroomLearnMetadataCandidate {
    pub(crate) metadata: HeadroomLearnMetadata,
    pub(crate) sort_key: Option<DateTime<Utc>>,
}

pub(crate) fn read_headroom_learn_metadata_from_path(
    path: &Path,
) -> Option<HeadroomLearnMetadataCandidate> {
    let content = std::fs::read_to_string(path).ok()?;
    let start = content.find("<!-- headroom:learn:start -->")?;
    let end = content.find("<!-- headroom:learn:end -->")?;
    if end <= start {
        return None;
    }

    let block = &content[start..end];
    let pattern_count = count_headroom_learn_patterns(block);
    let learned_at = parse_headroom_learn_timestamp(block);
    let modified_at = std::fs::metadata(path)
        .ok()
        .and_then(|meta| meta.modified().ok())
        .map(DateTime::<Utc>::from);

    Some(HeadroomLearnMetadataCandidate {
        metadata: HeadroomLearnMetadata {
            learned_at: learned_at
                .map(|timestamp| timestamp.to_rfc3339())
                .or_else(|| modified_at.map(|timestamp| timestamp.to_rfc3339())),
            pattern_count,
        },
        sort_key: learned_at.or(modified_at),
    })
}

fn count_headroom_learn_patterns(block: &str) -> Option<usize> {
    let count = block
        .lines()
        .filter(|line| line.trim_start().starts_with("- "))
        .count();

    if count > 0 {
        Some(count)
    } else {
        None
    }
}

fn parse_headroom_learn_timestamp(block: &str) -> Option<DateTime<Utc>> {
    const PREFIX: &str = "*Auto-generated by `headroom learn` on ";

    block.lines().find_map(|line| {
        let trimmed = line.trim();
        let rest = trimmed.strip_prefix(PREFIX)?;
        let token: String = rest
            .chars()
            .take_while(|ch| ch.is_ascii_digit() || matches!(ch, '-' | ':' | 'T' | 'Z' | '+'))
            .collect();
        if token.is_empty() {
            return None;
        }

        DateTime::parse_from_rfc3339(&token)
            .map(|timestamp| timestamp.with_timezone(&Utc))
            .ok()
            .or_else(|| {
                NaiveDate::parse_from_str(&token, "%Y-%m-%d")
                    .ok()
                    .and_then(|date| date.and_hms_opt(0, 0, 0))
                    .map(|timestamp| DateTime::<Utc>::from_naive_utc_and_offset(timestamp, Utc))
            })
    })
}

/// Parse sections and bullets inside the managed `<!-- headroom:learn -->`
/// block. Returns an empty Vec if no block is present.
pub fn parse_headroom_learn_block(file_content: &str) -> Vec<AppliedSection> {
    let Some(start) = file_content.find("<!-- headroom:learn:start -->") else {
        return Vec::new();
    };
    let Some(end_rel) = file_content[start..].find("<!-- headroom:learn:end -->") else {
        return Vec::new();
    };
    let block = &file_content[start..start + end_rel];

    let mut sections: Vec<AppliedSection> = Vec::new();
    let mut current: Option<AppliedSection> = None;

    for line in block.lines() {
        let trimmed = line.trim_start();
        if let Some(title) = trimmed.strip_prefix("### ") {
            if let Some(sec) = current.take() {
                sections.push(sec);
            }
            current = Some(AppliedSection {
                title: title.trim().to_string(),
                bullets: Vec::new(),
            });
        } else if let Some(sec) = current.as_mut() {
            if let Some(rest) = trimmed.strip_prefix("- ") {
                let bullet = rest.trim();
                if !bullet.is_empty() {
                    sec.bullets.push(bullet.to_string());
                }
            }
        }
    }
    if let Some(sec) = current {
        sections.push(sec);
    }
    sections
}

/// Delete one bullet from the managed block and return the updated file
/// contents. No-op (returns the original) when section or bullet is missing.
///
/// If a section's bullets are all removed, the whole `### <section>` block is
/// dropped. If the entire managed block becomes empty, the whole block
/// including its markers is removed.
pub fn delete_applied_bullet(file_content: &str, section_title: &str, bullet_text: &str) -> String {
    let Some(start) = file_content.find("<!-- headroom:learn:start -->") else {
        return file_content.to_string();
    };
    let end_marker = "<!-- headroom:learn:end -->";
    let Some(end_rel) = file_content[start..].find(end_marker) else {
        return file_content.to_string();
    };
    let end = start + end_rel + end_marker.len();

    let before = &file_content[..start];
    let block = &file_content[start..end];
    let after = &file_content[end..];

    let mut out_lines: Vec<String> = Vec::new();
    let mut current_section_start: Option<usize> = None;
    let mut current_section_has_bullets = false;
    let mut in_target_section = false;
    let mut bullet_removed = false;

    fn flush(
        out_lines: &mut Vec<String>,
        section_start: &mut Option<usize>,
        has_bullets: &mut bool,
    ) {
        if let Some(idx) = section_start.take() {
            if !*has_bullets {
                out_lines.truncate(idx);
            }
        }
        *has_bullets = false;
    }

    for line in block.lines() {
        // Skip the end-of-block marker so the section-flush truncation
        // can never drop it. We re-append it during reassembly below.
        if line.trim_end() == end_marker {
            continue;
        }

        let trimmed = line.trim_start();
        if let Some(title) = trimmed.strip_prefix("### ") {
            flush(
                &mut out_lines,
                &mut current_section_start,
                &mut current_section_has_bullets,
            );
            current_section_start = Some(out_lines.len());
            in_target_section = title.trim() == section_title;
            out_lines.push(line.to_string());
            continue;
        }

        if current_section_start.is_some() {
            if let Some(rest) = trimmed.strip_prefix("- ") {
                let bullet = rest.trim();
                if in_target_section && !bullet_removed && bullet == bullet_text {
                    bullet_removed = true;
                    continue;
                }
                if !bullet.is_empty() {
                    current_section_has_bullets = true;
                }
            }
        }

        out_lines.push(line.to_string());
    }
    flush(
        &mut out_lines,
        &mut current_section_start,
        &mut current_section_has_bullets,
    );

    if !bullet_removed {
        return file_content.to_string();
    }

    let any_sections = out_lines.iter().any(|l| l.trim_start().starts_with("### "));
    if !any_sections {
        let mut rewritten = String::with_capacity(before.len() + after.len());
        rewritten.push_str(before.trim_end_matches('\n'));
        let after_trimmed = after.trim_start_matches('\n');
        if !rewritten.is_empty() && !after_trimmed.is_empty() {
            rewritten.push_str("\n\n");
        }
        rewritten.push_str(after_trimmed);
        return rewritten;
    }

    // Drop trailing blank lines so removing the last bullet of the last
    // section doesn't leave a `\n\n<!-- end -->` gap behind.
    while out_lines
        .last()
        .map(|s| s.trim().is_empty())
        .unwrap_or(false)
    {
        out_lines.pop();
    }

    let mut rewritten = String::with_capacity(file_content.len());
    rewritten.push_str(before);
    rewritten.push_str(&out_lines.join("\n"));
    rewritten.push('\n');
    rewritten.push_str(end_marker);
    rewritten.push_str(after);
    rewritten
}

pub fn claude_project_memory_file(project_path: &str) -> PathBuf {
    let home = dirs::home_dir()
        .or_else(|| std::env::var_os("HOME").map(PathBuf::from))
        .unwrap_or_else(std::env::temp_dir);
    home.join(".claude")
        .join("projects")
        .join(encode_claude_project_folder_name(project_path))
        .join("memory")
        .join("MEMORY.md")
}

fn encode_claude_project_folder_name(project_path: &str) -> String {
    format!(
        "-{}",
        project_path.trim_start_matches('/').replace('/', "-")
    )
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::{
        count_headroom_learn_patterns, delete_applied_bullet, encode_claude_project_folder_name,
        parse_headroom_learn_block, parse_headroom_learn_timestamp,
        read_headroom_learn_metadata_from_path,
    };

    #[test]
    fn parse_headroom_learn_timestamp_accepts_generated_date_lines() {
        let block = r#"
<!-- headroom:learn:start -->
## Headroom Learned Patterns
*Auto-generated by `headroom learn` on 2026-03-26 — do not edit manually*
- First pattern
<!-- headroom:learn:end -->
"#;

        let timestamp = parse_headroom_learn_timestamp(block).expect("timestamp");

        assert_eq!(timestamp.to_rfc3339(), "2026-03-26T00:00:00+00:00");
    }

    #[test]
    fn count_headroom_learn_patterns_counts_bullets_inside_block() {
        let block = r#"
<!-- headroom:learn:start -->
- First pattern
*Auto-generated by `headroom learn` on 2026-03-26 — do not edit manually*
- Second pattern
<!-- headroom:learn:end -->
"#;

        assert_eq!(count_headroom_learn_patterns(block), Some(2));
    }

    #[test]
    fn count_headroom_learn_patterns_returns_none_for_block_with_no_bullets() {
        let block = r#"
<!-- headroom:learn:start -->
*Auto-generated by `headroom learn` on 2026-03-26 — do not edit manually*
<!-- headroom:learn:end -->
"#;

        assert_eq!(count_headroom_learn_patterns(block), None);
    }

    #[test]
    fn count_headroom_learn_patterns_ignores_non_bullet_lines() {
        let block = r#"
<!-- headroom:learn:start -->
## Heading
Plain text without a dash
- Real pattern
<!-- headroom:learn:end -->
"#;

        assert_eq!(count_headroom_learn_patterns(block), Some(1));
    }

    #[test]
    fn parse_headroom_learn_timestamp_returns_none_when_no_timestamp_line() {
        let block = r#"
<!-- headroom:learn:start -->
- Some pattern
<!-- headroom:learn:end -->
"#;

        assert!(parse_headroom_learn_timestamp(block).is_none());
    }

    #[test]
    fn parse_headroom_learn_timestamp_accepts_rfc3339_datetime() {
        let block = r#"
<!-- headroom:learn:start -->
*Auto-generated by `headroom learn` on 2026-03-26T14:30:00Z — do not edit manually*
- Pattern
<!-- headroom:learn:end -->
"#;

        let timestamp = parse_headroom_learn_timestamp(block).expect("timestamp");

        assert_eq!(timestamp.to_rfc3339(), "2026-03-26T14:30:00+00:00");
    }

    #[test]
    fn parse_block_extracts_sections_and_bullets() {
        let content = r#"# Prior heading

<!-- headroom:learn:start -->
## Headroom Learned Patterns
*Auto-generated by `headroom learn` on 2026-04-22 — do not edit manually*

### Large Files
*~15,000 tokens/session saved*
- `src/App.tsx` is very large
- Also `lib.rs`

### Learned: environment
- Use uv run python
<!-- headroom:learn:end -->
"#;

        let sections = parse_headroom_learn_block(content);
        assert_eq!(sections.len(), 2);
        assert_eq!(sections[0].title, "Large Files");
        assert_eq!(
            sections[0].bullets,
            vec!["`src/App.tsx` is very large", "Also `lib.rs`"]
        );
        assert_eq!(sections[1].title, "Learned: environment");
        assert_eq!(sections[1].bullets, vec!["Use uv run python"]);
    }

    #[test]
    fn parse_block_returns_empty_when_no_block_present() {
        let content = "Just some CLAUDE.md content without markers.\n- a bullet";
        assert!(parse_headroom_learn_block(content).is_empty());
    }

    #[test]
    fn delete_applied_bullet_removes_one_bullet() {
        let content = "\
before
<!-- headroom:learn:start -->
### Foo
- alpha
- beta
- gamma
<!-- headroom:learn:end -->
after
";
        let out = delete_applied_bullet(content, "Foo", "beta");
        assert!(out.contains("- alpha"));
        assert!(!out.contains("- beta"));
        assert!(out.contains("- gamma"));
        assert!(out.contains("### Foo"));
    }

    #[test]
    fn delete_applied_bullet_drops_section_when_last_bullet_removed() {
        let content = "\
<!-- headroom:learn:start -->
### Foo
- only
### Bar
- keep
<!-- headroom:learn:end -->
";
        let out = delete_applied_bullet(content, "Foo", "only");
        assert!(!out.contains("### Foo"));
        assert!(out.contains("### Bar"));
        assert!(out.contains("- keep"));
    }

    #[test]
    fn delete_applied_bullet_drops_last_section_and_keeps_end_marker() {
        // Regression: previously the final flush truncated the trailing
        // `<!-- headroom:learn:end -->` marker when the last section was
        // emptied, which left the block unparseable on the next read.
        let content = "\
<!-- headroom:learn:start -->
### Foo
- keep
### Bar
- removeme
<!-- headroom:learn:end -->
";
        let out = delete_applied_bullet(content, "Bar", "removeme");
        assert!(out.contains("### Foo"), "earlier section preserved");
        assert!(out.contains("- keep"), "earlier bullet preserved");
        assert!(!out.contains("### Bar"), "emptied last section dropped");
        assert!(!out.contains("- removeme"), "removed bullet absent");
        assert!(
            out.contains("<!-- headroom:learn:end -->"),
            "end marker preserved, got:\n{out}"
        );
        assert!(
            !parse_headroom_learn_block(&out).is_empty(),
            "block still parseable after deletion"
        );
    }

    #[test]
    fn delete_applied_bullet_removes_whole_block_when_empty() {
        let content = "prefix\n\n<!-- headroom:learn:start -->\n### Foo\n- only\n<!-- headroom:learn:end -->\n\nsuffix\n";
        let out = delete_applied_bullet(content, "Foo", "only");
        assert!(!out.contains("headroom:learn:start"));
        assert!(!out.contains("headroom:learn:end"));
        assert!(out.contains("prefix"));
        assert!(out.contains("suffix"));
    }

    #[test]
    fn delete_applied_bullet_is_noop_when_bullet_missing() {
        let content =
            "<!-- headroom:learn:start -->\n### Foo\n- alpha\n<!-- headroom:learn:end -->\n";
        let out = delete_applied_bullet(content, "Foo", "not-there");
        assert_eq!(out, content);
    }

    #[test]
    fn parse_headroom_learn_timestamp_returns_none_for_malformed_date() {
        let block = r#"
<!-- headroom:learn:start -->
*Auto-generated by `headroom learn` on not-a-date — do not edit manually*
- Pattern
<!-- headroom:learn:end -->
"#;

        assert!(parse_headroom_learn_timestamp(block).is_none());
    }

    #[test]
    fn encode_claude_project_folder_name_replaces_slashes_preserving_hyphens() {
        // Claude Code's on-disk encoding only substitutes '/' with '-'; literal
        // hyphens in the path are preserved verbatim. Verified against real
        // ~/.claude/projects/ folder names.
        assert_eq!(
            encode_claude_project_folder_name("/Users/alice/my-project"),
            "-Users-alice-my-project"
        );
    }

    #[test]
    fn encode_claude_project_folder_name_handles_root_slash() {
        assert_eq!(encode_claude_project_folder_name("/foo"), "-foo");
    }

    #[test]
    fn read_headroom_learn_metadata_from_path_falls_back_to_file_metadata() {
        let root = unique_temp_dir("headroom-learn-metadata");
        fs::create_dir_all(&root).expect("create root");
        let memory = root.join("MEMORY.md");
        fs::write(
            &memory,
            r#"
<!-- headroom:learn:start -->
- First pattern
- Second pattern
<!-- headroom:learn:end -->
"#,
        )
        .expect("write memory file");

        let metadata = read_headroom_learn_metadata_from_path(&memory).expect("metadata");

        assert_eq!(metadata.metadata.pattern_count, Some(2));
        assert!(metadata.metadata.learned_at.is_some());
        assert!(metadata.sort_key.is_some());

        let _ = fs::remove_dir_all(root);
    }

    fn unique_temp_dir(prefix: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time went backwards")
            .as_nanos();
        std::env::temp_dir().join(format!("{prefix}-{nanos}"))
    }
}
